services:
  _defaults:
      autowire: true

  oloy.earning_rule.command_handler:
    class: OpenLoyalty\Component\EarningRule\Domain\Command\EarningRuleCommandHandler
    arguments:
      - '@oloy.earning_rule.repository'
      - '@broadway.uuid.generator'
    lazy: true
    tags:
      - { name: broadway.command_handler }
  oloy.earning_rule.repository:
    class: OpenLoyalty\Component\EarningRule\Infrastructure\Persistence\Doctrine\Repository\DoctrineEarningRuleRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Component\EarningRule\Domain\EarningRule'
  oloy.earning_rule.usage_repository:
    class: OpenLoyalty\Component\EarningRule\Infrastructure\Persistence\Doctrine\Repository\DoctrineEarningRuleUsageRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Component\EarningRule\Domain\EarningRuleUsage'
  oloy.earning_rule.algorithm.points_earning:
    class: OpenLoyalty\Component\EarningRule\Domain\Algorithm\PointsEarningRuleAlgorithm
    tags:
      - { name: oloy.earning_rule.algorithm, alias: PointsEarningRule }
  oloy.earning_rule.algorithm.product_purchase:
    class: OpenLoyalty\Component\EarningRule\Domain\Algorithm\ProductPurchaseEarningRuleAlgorithm
    tags:
      - { name: oloy.earning_rule.algorithm, alias: ProductPurchaseEarningRule }
  oloy.earning_rule.algorithm.multiply_points_for_product:
    class: OpenLoyalty\Component\EarningRule\Domain\Algorithm\MultiplyPointsForProductRuleAlgorithm
    tags:
      - { name: oloy.earning_rule.algorithm, alias: MultiplyPointsForProductEarningRule }
  oloy.earning_rule.algorithm.multiply_points_by_product_labels:
    class: OpenLoyalty\Component\EarningRule\Domain\Algorithm\MultiplyPointsByProductLabelsRuleAlgorithm
    tags:
      - { name: oloy.earning_rule.algorithm, alias: MultiplyPointsByProductLabelsEarningRule }
  OpenLoyalty\Component\EarningRule\Domain\Algorithm\InstantRewardRuleAlgorithm:
    class: OpenLoyalty\Component\EarningRule\Domain\Algorithm\InstantRewardRuleAlgorithm
    arguments:
      - '@OpenLoyalty\Component\EarningRule\Domain\Strategy\InstantRewardEarningRuleStrategy'
      - "@broadway.command_handling.command_bus"
    tags:
      - { name: oloy.earning_rule.algorithm, alias: InstantRewardRule }
  OpenLoyalty\Component\EarningRule\Domain\Strategy\InstantRewardEarningRuleStrategy:
    class: OpenLoyalty\Component\EarningRule\Domain\Strategy\InstantRewardEarningRuleStrategy
    arguments:
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\EarningRuleCampaignProvider'
  OpenLoyalty\Component\EarningRule\Domain\OloyEarningRuleEvaluator:
    arguments:
      $earningRuleRepository: '@oloy.earning_rule.repository'
      $transactionDetailsRepository: '@oloy.transaction.read_model.repository.transaction_details'
      $algorithmFactory: '@oloy.earning_rule.algorithm_factory'
      $invitationDetailsRepository: '@oloy.user.read_model.repository.invitation_details'
      $segmentedCustomerElasticSearchRepository: '@oloy.segment.read_model.repository.segmented_customers'
      $customerDetailsRepository: '@oloy.user.read_model.repository.customer_details'
      $settingsManager: '@ol.settings.manager'
      $stoppableProvider: '@OpenLoyalty\Component\EarningRule\Domain\Stoppable\StoppableProvider'
  OpenLoyalty\Component\EarningRule\Domain\Stoppable\StoppableProvider: ~
