services:
  _defaults:
    autowire: true
    autoconfigure: true

  oloy.points.account.command_handler:
    class: OpenLoyalty\Component\Account\Domain\Command\AccountCommandHandler
    arguments:
      - '@oloy.points.account.repository'
      - '@broadway.event_dispatcher'
    lazy: true
    tags:
      - { name: broadway.command_handler }
  oloy.points.account.repository:
    class: OpenLoyalty\Component\Account\Domain\AccountRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - ['@broadway.metadata_enriching_event_stream_decorator']
  OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetailsRepository:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.points_transfer_details'
      - 'OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetails'
      - 'OpenLoyalty\Component\Account\Infrastructure\Repository\PointsTransferDetailsElasticsearchRepository'
  oloy.points.account.read_model.projector.point_transfer_details:
    class: 'OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      $repository: '@oloy.points.account.repository.points_transfer_details'
      $accountRepository: '@oloy.points.account.repository.account_details'
      $customerRepository: '@oloy.user.read_model.repository.customer_details'
      $posRepository: '@oloy.pos.repository'

  oloy.points.account.repository.account_details:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.account_details'
      - 'OpenLoyalty\Component\Account\Domain\ReadModel\AccountDetails'
  oloy.points.account.read_model.projector.account_details:
    class: 'OpenLoyalty\Component\Account\Domain\ReadModel\AccountDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.points.account.repository.account_details'
  oloy.points.apply_earning_rule_listener.transaction:
    class: 'OpenLoyalty\Component\Account\Infrastructure\SystemEvent\Listener\ApplyEarningRuleToTransactionListener'
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.points.account.repository.account_details'
      - '@broadway.uuid.generator'
      - '@OpenLoyalty\Component\EarningRule\Domain\OloyEarningRuleEvaluator'
    tags:
      - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: onRegisteredTransaction}
  oloy.points.apply_earning_rule_listener.event:
    class: 'OpenLoyalty\Component\Account\Infrastructure\SystemEvent\Listener\ApplyEarningRuleToEventListener'
    arguments:
       $commandBus: '@broadway.command_handling.command_bus'
       $accountDetailsRepository: '@oloy.points.account.repository.account_details'
       $uuidGenerator: '@broadway.uuid.generator'
       $earningRuleApplier: '@OpenLoyalty\Component\EarningRule\Domain\OloyEarningRuleEvaluator'
       $earningRuleLimitValidator: '@oloy.earning_rule.validator'
    tags:
      - { name: broadway.event_listener, event: oloy.account.created, method: onCustomerRegistered}
      - { name: broadway.event_listener, event: oloy.transaction.customer_first_transaction, method: onFirstTransaction}
      - { name: broadway.event_listener, event: oloy.customer.logged_in, method: onCustomerLogin}
      - { name: broadway.event_listener, event: oloy.customer.newsletter_subscription, method: onNewsletterSubscription }
      - { name: broadway.event_listener, event: oloy.account.custom_event_occured, method: onCustomEvent }
      - { name: broadway.event_listener, event: oloy.invitation.customer_attached, method: onCustomerAttachedToInvitation }
  oloy.account.spend_points_on_campaign_listener:
      class: OpenLoyalty\Component\Account\Infrastructure\Event\Listener\SpendPointsOnCampaignListener
      arguments:
        - '@broadway.command_handling.command_bus'
        - '@oloy.points.account.repository.account_details'
        - '@broadway.uuid.generator'
      lazy: true
      tags:
        - { name: broadway.domain.event_listener }

  oloy.account.revoke_points_on_return_transaction_listener:
      class: OpenLoyalty\Component\Account\Infrastructure\Event\Listener\RevokePointsOnReturnTransactionListener
      arguments:
        $transfersRepo: '@oloy.points.account.repository.points_transfer_details'
        $accountDetailsRepository: '@oloy.points.account.repository.account_details'
        $commandBus: '@broadway.command_handling.command_bus'
        $uuidGenerator: '@broadway.uuid.generator'
      lazy: true
      tags:
        - { name: broadway.domain.event_listener }
