services:
  oloy.account.form_type.add_points:
      class: OpenLoyalty\Bundle\PointsBundle\Form\Type\AddPointsFormType
      arguments:
        - '@oloy.user.read_model.repository.customer_details'
      tags:
        - { name: form.type }
  oloy.account.form_type.spend_points:
      class: OpenLoyalty\Bundle\PointsBundle\Form\Type\SpendPointsFormType
      parent: 'oloy.account.form_type.add_points'
      tags:
        - { name: form.type }
  oloy.account.points_transfers_manager:
      class: OpenLoyalty\Bundle\PointsBundle\Service\PointsTransfersManager
      arguments:
        - '@broadway.command_handling.command_bus'
        - '@oloy.points.account.repository.points_transfer_details'
        - '@ol.settings.manager'
  oloy.account.points_transfers.serialization_listener:
      class: OpenLoyalty\Bundle\PointsBundle\Event\Listener\PointsTransferSerializationListener
      arguments:
        - '@ol.settings.manager'
        - '@oloy.pos.repository'
        - '@oloy.transaction.read_model.repository.transaction_details'
      tags:
        - { name: jms_serializer.event_subscriber }

  oloy.account.points_transfers.param_converter:
    class: OpenLoyalty\Bundle\PointsBundle\ParamConverter\PointsTransferParamConverter
    arguments: ['@oloy.points.account.repository.points_transfer_details']
    tags:
      - { name: request.param_converter, priority: 2, converter: points_transfer_converter }
  oloy.account.listener.available_points_amount_changed:
    class: OpenLoyalty\Bundle\PointsBundle\Event\Listener\AvailablePointsAmountChangedListener
    arguments: ['@oloy.user.email_provider', '@oloy.user.read_model.repository.customer_details']
    tags:
      - { name: broadway.event_listener, method: onChange, event: oloy.account.available_points_amount_changed}

  oloy.account.points_transfers.import.points_transfer_node_streamer:
    class: OpenLoyalty\Bundle\ImportBundle\Importer\XMLUniqueNodeStringFileStreamer
    arguments:
        - "pointsTransfer"

  oloy.account.points_transfers.import.points_transfer_import_processor:
    class: OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferImportProcessor
    arguments:
        - "@broadway.command_handling.command_bus"

  oloy.account.points_transfers.import.points_transfer_xml_import_converter:
    class: OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImportConverter
    arguments:
        - "@broadway.uuid.generator"
        - "@oloy.points.account.repository.account_details"

  oloy.account.points_transfers.import.points_transfer_importer:
    parent: "oloy.import.importer.xml_importer"
    calls:
      - [setProcessor, ['@oloy.account.points_transfers.import.points_transfer_import_processor']]
      - [setXmlStreamer, ['@oloy.account.points_transfers.import.points_transfer_node_streamer']]
      - [setConverter, ['@oloy.account.points_transfers.import.points_transfer_xml_import_converter']]
