services:
  _defaults:
    autowire: true

  oloy.campaign.command_handler:
    class: OpenLoyalty\Component\Campaign\Domain\Command\CampaignCommandHandler
    arguments:
      - '@oloy.campaign.repository'
    tags:
      - { name: broadway.command_handler }
  OpenLoyalty\Component\Campaign\Domain\Command\InstantRewardHandler:
    arguments:
      $campaignRepository: '@oloy.campaign.repository'
      $commandBus: '@broadway.command_handling.command_bus'
    tags:
      - { name: broadway.command_handler }
  OpenLoyalty\Component\Campaign\Domain\Command\BuyCampaignHandler:
    arguments:
      $campaignRepository: '@oloy.campaign.repository'
      $commandBus: '@broadway.command_handling.command_bus'
    tags:
      - { name: broadway.command_handler }
  oloy.campaign.repository:
    class: OpenLoyalty\Component\Campaign\Infrastructure\Persistence\Doctrine\Repository\DoctrineCampaignRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Component\Campaign\Domain\Campaign'
  oloy.campaign.read_model.repository.coupon_usage:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.coupon_usage'
      - 'OpenLoyalty\Component\Campaign\Domain\ReadModel\CouponUsage'
      - 'OpenLoyalty\Component\Campaign\Infrastructure\Repository\CouponUsageElasticsearchRepository'
  oloy.campaign.read_model.projector.coupon_usage:
    class: OpenLoyalty\Component\Campaign\Infrastructure\ReadModel\CouponUsageProjector
    arguments:
      - '@oloy.campaign.read_model.repository.coupon_usage'
    lazy: true
    tags:
      - { name: broadway.domain.event_listener }
  oloy.campaign.read_model.repository.campaign_usage:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.campaign_usage'
      - 'OpenLoyalty\Component\Campaign\Domain\ReadModel\CampaignUsage'
      - 'OpenLoyalty\Component\Campaign\Infrastructure\Repository\CampaignUsageElasticsearchRepository'
  oloy.campaign.read_model.projector.campaign_usage:
    class: OpenLoyalty\Component\Campaign\Domain\ReadModel\CampaignUsageProjector
    arguments:
      - '@oloy.campaign.read_model.repository.campaign_usage'
    calls:
      - [setLogger, ['@logger']]
    tags:
      - { name: broadway.domain.event_listener }
  oloy.campaign.read_model.repository.campaign_bought:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.campaign_bought'
      - 'OpenLoyalty\Component\Campaign\Domain\ReadModel\CampaignBought'
      - 'OpenLoyalty\Component\Campaign\Infrastructure\Repository\CampaignBoughtElasticsearchRepository'
  oloy.campaign.read_model.projector.campaign_bought:
    class: OpenLoyalty\Component\Campaign\Domain\ReadModel\CampaignBoughtProjector
    arguments:
      - '@oloy.campaign.read_model.repository.campaign_bought'
      - '@oloy.campaign.repository'
    tags:
      - { name: broadway.domain.event_listener }
  OpenLoyalty\Component\Campaign\Domain\Coupon\CouponCodeProvider:
    class: OpenLoyalty\Component\Campaign\Domain\Coupon\CouponCodeProvider
    arguments:
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignProvider'
  OpenLoyalty\Component\Campaign\Domain\Provider\CouponActivationDateProvider: ~
  OpenLoyalty\Component\Campaign\Domain\Provider\CouponExpirationDateProvider: ~
