services:
  _defaults:
    autowire: true
    autoconfigure: true

  OpenLoyalty\Bundle\CampaignBundle\Controller\Api\:
      resource: '../../Controller/Api/*'
      tags: ['controller.service_arguments']

  Broadway\CommandHandling\CommandBus: '@broadway.command_handling.command_bus'
  Symfony\Component\Translation\TranslationInterface: '@translator'

  oloy.campaign.form_type.campaign:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.edit_campaign:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\EditCampaignFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.campaign_activity:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignActivityFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.campaign_visibility:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignVisibilityFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.labels:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\LabelsFormType
    tags:
      - { name: form.type }
  oloy.campaign.param_converter:
    class: OpenLoyalty\Bundle\CampaignBundle\ParamConverter\CampaignParamConverter
    arguments: ['@oloy.campaign.repository']
    tags:
      - { name: request.param_converter, priority: 2, converter: campaign_converter }
  OpenLoyalty\Bundle\CampaignBundle\Service\CampaignProvider:
    arguments:
      - '@oloy.segment.read_model.repository.segmented_customers'
      - '@oloy.user.read_model.repository.customers_belonging_to_one_level'
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignValidator'
      - '@oloy.campaign.read_model.repository.campaign_usage'
      - '@oloy.campaign.repository'

  OpenLoyalty\Bundle\CampaignBundle\Service\CampaignValidator:
    arguments:
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@oloy.points.account.repository.account_details'
      - '@ol.settings.manager'
  OpenLoyalty\Bundle\CampaignBundle\Service\EarningRuleCampaignProvider:
    class: OpenLoyalty\Bundle\CampaignBundle\Service\EarningRuleCampaignProvider
    arguments:
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignProvider'
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignValidator'
      - '@oloy.campaign.repository'
  oloy.campaign.serialization_listener:
    class: OpenLoyalty\Bundle\CampaignBundle\Event\Listener\CampaignSerializationListener
    autowire: true
    arguments:
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignValidator'
      - '@oloy.segment.repository'
      - '@oloy.level.repository'
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@OpenLoyalty\Bundle\CampaignBundle\Service\CampaignProvider'
      - '@oloy.campaign.read_model.repository.campaign_usage'
      - '@oloy.customer_status_provider'
    tags:
      - { name: jms_serializer.event_subscriber }

  oloy.campaign.photos_filesystem:
    class:     Gaufrette\Filesystem
    factory:   ['@knp_gaufrette.filesystem_map', get]
    arguments: ['campaign_photos']

  oloy.campaign.photo_uploader:
    class: OpenLoyalty\Bundle\CampaignBundle\Service\CampaignPhotoUploader
    arguments: ["@oloy.campaign.photos_filesystem"]

  oloy.campaign.validator.image:
    class: OpenLoyalty\Bundle\CampaignBundle\Validator\Constraints\ImageValidator
    arguments:
      - '%oloy.campaign.photos_min_width%'
      - '%oloy.campaign.photos_min_height%'
    tags:
      - { name: validator.constraint_validator }
  OpenLoyalty\Bundle\CampaignBundle\Command\SetCouponsAsActiveCommand:
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@broadway.command_handling.command_bus'
      - '@logger'
    tags:
      - { name: 'console.command', command: 'oloy:coupons:set_active' }
  OpenLoyalty\Bundle\CampaignBundle\Command\SetCouponsAsExpiredCommand:
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@broadway.command_handling.command_bus'
      - '@logger'
    tags:
      - { name: 'console.command', command: 'oloy:coupons:set_expired' }
  OpenLoyalty\Bundle\CampaignBundle\Service\MultipleCampaignCouponUsageProvider:
    arguments:
      - '@oloy.campaign.repository'
      - '@oloy.user.read_model.repository.customer_details'
      - '@translator'
