services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    OpenLoyalty\Bundle\EmailSettingsBundle\Command\AddEmailTemplate: ~

    OpenLoyalty\Bundle\EmailSettingsBundle\Service\EmailSettings:
        arguments: ['%oloy.email.emails%', '@twig.loader.filesystem', '@twig']
        calls:
          - ['addDefaultSettings', ['mailer_from_name', '%mailer_from_name%']]
          - ['addDefaultSettings', ['mailer_from_address', '%mailer_from_address%']]

    OpenLoyalty\Bundle\EmailSettingsBundle\Form\Type\EmailFormType:
        tags:
          - { name: form.type }
