OpenLoyalty\Component\Level\Domain\Level:
  exlusion_policy: ALL
  properties:
    levelId:
      expose: true
      inline: true
    photo:
      exclude: true
  virtual_properties:
    hasLevelPhoto:
      serialized_name: hasPhoto
      type: boolean